name: RedSpeed
main: de.redstoneworld.redspeed.RedSpeed
version: 1.1.4
api-version: 1.19
description: A small speed plugin to change the walk- and fly-speed for yourself or and other player.
authors: [RedstoneFuture]
website: https://redstoneworld.de
commands:
  redwalkspeed:
    description: Show or define your walk speed.
    usage: /wspeed [walk-speed | 'back'] [player]
    aliases: [walkspeed, wspeed, ws]
  redflyspeed:
    description: Show or define your fly speed.
    usage: /fspeed [fly-speed | 'back'] [player]
    aliases: [flyspeed, fspeed, fs]